/* Lesson 2: Filtering Query Results and Data type functions

Main Agenda:
    - Filter Query Results
    - Data types in SQL Server
    - SQL data type functions */

--Homework

/* Exercise 1: From AdventureWorksDW2019 database, FactInternetSales table,
take all the output that has OrderDate from '2011-01-01' to the latest and ShipDate within 2011 */  

USE AdventureWorksDW2019
SELECT *
FROM FactInternetSales
WHERE OrderDate >= '2011-01-01'
AND YEAR(ShipDate) = 2011

/*Exercise 2: From AdventureWorksDW2019 database, DimProduct table,
select ProductKey column, ProductAlternateKey column and EnglishProductName column.
Filter the products that has ProductAlternateKey start with 'BK-', after that is a random character but letter T, and end with 2 random number.
Another condition is that the Color is Black or Red or White */  

USE AdventureWorksDW2019
SELECT
    ProductKey,
    ProductAlternateKey,
    EnglishProductName
FROM DimProduct
WHERE ProductAlternateKey LIKE 'BK-[^T]%-[0-9][0-9]'
AND Color IN ('Black','Red','White')

/* Exercise 3: From AdventureWorksDW2019 database, DimProduct table, select all the product that has Red color */  

USE AdventureWorksDW2019
Select *
FROM DimProduct
WHERE Color='Red'

/* Exercise 4: From AdventureWorksDW2019 database, FactInternetSales table that include product sold information,  
take the output of the products that has Red color */  

USE AdventureWorksDW2019
SELECT *
FROM FactInternetSales
WHERE ProductKey IN(SELECT
                        ProductKey
                    FROM DimProduct
                    WHERE Color='Red')

/* Exercise 5: From AdventureWorksDW2019, DimEmployee table, 
select EmployeeKey column, FirstName column, LastName column, MiddleName column of the employee that has MiddleName (not Null)
and Phone cell that has 12 characters */

USE AdventureWorksDW2019
SELECT TOP 10
    EmployeeKey,
    FirstName,
    LastName,
    MiddleName,
    Phone
FROM DimEmployee
WHERE MiddleName IS NOT NULL 
AND LEN(Phone)=12


/* Ex6: From AdventureWorksDW2019 database, DimEmployee table, select EmployeeKey 

And namy more columns:  

a. FullName column, generated by: FirstName column, MiddleName column and LastName column, with space between  

b. AgeHired column, calculating employee's age by the time they get hired, generated by using HireDate column and BirthDate column 

c. AgeNow column, calculating employee's current age, generated by using BirthDate column 

d. UserName column, generated by using the part after the character "\" of LoginID column
(For example: LoginID = adventure-works\jun0, so the UserName output is jun0) */  

USE AdventureWorksDW2019 
Select 
    EmployeeKey,
    FirstName + ' ' + ISNULL(MiddleName + ' ','') + LastName AS 'FullName',
    Datediff(year,BirthDate,HireDate) AS 'AgeHired',
    Datediff(year,BirthDate,CURRENT_TIMESTAMP) as 'AgeNow',
    RIGHT(LoginID, CHARINDEX('\', REVERSE(LoginID)) - 1) AS 'UserName'
FROM DimEmployee
